# Generated by Django 5.2.14 on 2026-06-02 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productimage_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['variant_id', '-is_primary', 'sort_order', 'id']},
        ),
    ]
