# Generated by Django 5.2.14 on 2026-06-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color_mix',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
