# Generated by Django 5.2.14 on 2026-06-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariant_color_mix'),
        ('shipping', '0002_internationalshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='international_shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shipping.internationalshipping'),
        ),
    ]
