# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="taxonomy_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("product_family", "Product family"),
                    ("audience", "Audience"),
                    ("height", "Height"),
                    ("purpose", "Purpose"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["taxonomy_group", "is_active"], name="categories_taxonom_3f151d_idx"),
        ),
    ]
