# Generated by Django 5.2.14 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_category_taxonomy_group'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='categories_taxonom_347a25_idx',
            old_name='categories_taxonom_3f151d_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
    ]
