# Generated by Django 5.2.14 on 2026-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_categories_taxonom_3f151d_idx_categories_taxonom_347a25_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='taxonomy_group',
            field=models.CharField(blank=True, choices=[('product_family', 'Product family'), ('audience', 'Audience'), ('height', 'Height'), ('purpose', 'Purpose'), ('style', 'Style')], default='', max_length=32),
        ),
    ]
