# Generated by Django 5.2.13 on 2026-04-12 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartbundleitem',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.bundle'),
        ),
        migrations.AddField(
            model_name='cartbundleitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartvariantitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_items', to='cart.cart'),
        ),
        migrations.AddField(
            model_name='cartvariantitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartbundleitem',
            unique_together={('cart', 'bundle')},
        ),
        migrations.AlterUniqueTogether(
            name='cartvariantitem',
            unique_together={('cart', 'variant')},
        ),
    ]
