# Generated by Django 6.0 on 2026-05-08 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_initial'),
        ('discounts', '0006_discountclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_discount_claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.discountclaim'),
        ),
    ]
