# Generated by Django 5.2.14 on 2026-07-14 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_homepage_tiles(apps, schema_editor):
    HomepageTile = apps.get_model("content", "HomepageTile")
    defaults = (
        ("women", "Women", "/collections/women", 10),
        ("men", "Men", "/collections/men", 20),
        ("kids", "Kids", "/collections/kids", 30),
    )
    for key, title, href, sort_order in defaults:
        HomepageTile.objects.create(
            key=key,
            title=title,
            href=href,
            sort_order=sort_order,
            alt_text=f"Shop {title}",
        )


def remove_default_homepage_tiles(apps, schema_editor):
    HomepageTile = apps.get_model("content", "HomepageTile")
    HomepageTile.objects.filter(key__in=("women", "men", "kids")).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage-tiles/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'homepage_tiles',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(
            seed_default_homepage_tiles,
            remove_default_homepage_tiles,
        ),
    ]
