# Generated by Django 5.2.14 on 2026-08-20 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_seed_teens_homepage_tile'),
        ('products', '0007_product_international_shipping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('partner_name', models.CharField(blank=True, max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='collabs/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='collabs/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='collabs/')),
                ('accent_color', models.CharField(default='#253E38', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('cta_label', models.CharField(default='Shop the collection', max_length=80)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_homepage', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='collabs', to='products.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collabs',
                'ordering': ['sort_order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='collabs_slug_b8812d_idx'), models.Index(fields=['is_active', 'show_on_homepage'], name='collabs_is_acti_a022a9_idx')],
            },
        ),
    ]
