# Generated by Django 5.2.14 on 2026-08-21 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_collab'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteimage',
            name='video',
            field=models.FileField(blank=True, help_text='Optional background video for slots that support one.', null=True, upload_to='site/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v', 'ogg'])]),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
