# Generated by Django 6.0 on 2026-05-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('topic', models.CharField(choices=[('order', 'Order help'), ('returns', 'Returns and exchanges'), ('sizing', 'Sizing help'), ('product', 'Product question'), ('general', 'General question')], default='general', max_length=24)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('resolved', 'Resolved')], default='new', max_length=24)),
            ],
            options={
                'db_table': 'contact_submissions',
                'ordering': ('-created_at',),
            },
        ),
    ]
