# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="checkout_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider_reference_id",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
