# Generated by Django 5.2.13 on 2026-04-12 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0002_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountrule',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='coupon_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discounts.couponcode'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='discount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount'),
        ),
    ]
