# Generated by Django 6.0 on 2026-05-08 10:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_discountusage_email_alter_discountusage_user_and_more'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('status', models.CharField(choices=[('claimed', 'Claimed'), ('applied', 'Applied'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='claimed', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='discounts.couponcode')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='discounts.discount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_claims', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'discount_claims',
                'indexes': [models.Index(fields=['discount', 'email', 'status'], name='discount_cl_discoun_dc48f3_idx'), models.Index(fields=['token', 'status'], name='discount_cl_token_4fb635_idx')],
            },
        ),
    ]
