# Generated by Codex on 2026-05-08

from decimal import Decimal

from django.db import migrations


def set_first_order_discount_to_20(apps, schema_editor):
    Discount = apps.get_model("discounts", "Discount")
    CouponCode = apps.get_model("discounts", "CouponCode")

    discount = Discount.objects.filter(first_order_only=True).order_by("id").first()
    if not discount:
        discount = Discount.objects.create(
            name="FIRST20",
            discount_type="percent",
            percentage=Decimal("20.00"),
            first_order_only=True,
            is_active=True,
            is_auto_applied=False,
            is_stackable=False,
        )
    else:
        discount.name = "FIRST20"
        discount.discount_type = "percent"
        discount.percentage = Decimal("20.00")
        discount.flat_amount = None
        discount.first_order_only = True
        discount.is_active = True
        discount.is_stackable = False
        discount.save(
            update_fields=[
                "name",
                "discount_type",
                "percentage",
                "flat_amount",
                "first_order_only",
                "is_active",
                "is_stackable",
                "updated_at",
            ]
        )

    coupon = CouponCode.objects.filter(discount=discount).order_by("id").first()
    if coupon:
        if coupon.code != "FIRST20" and not CouponCode.objects.filter(code="FIRST20").exclude(id=coupon.id).exists():
            coupon.code = "FIRST20"
        coupon.is_active = True
        coupon.save(update_fields=["code", "is_active", "updated_at"])
    else:
        CouponCode.objects.get_or_create(
            code="FIRST20",
            defaults={"discount": discount, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0006_discountclaim"),
    ]

    operations = [
        migrations.RunPython(set_first_order_discount_to_20, migrations.RunPython.noop),
    ]
