# Generated by Codex on 2026-05-08

from django.db import migrations


def clear_first_order_discount_window(apps, schema_editor):
    Discount = apps.get_model("discounts", "Discount")
    Discount.objects.filter(first_order_only=True).update(starts_at=None, expires_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0007_first_order_discount_20"),
    ]

    operations = [
        migrations.RunPython(clear_first_order_discount_window, migrations.RunPython.noop),
    ]
