# Generated by Codex on 2026-05-08

from decimal import Decimal

from django.db import migrations


def clear_first_order_discount_minimum(apps, schema_editor):
    Discount = apps.get_model("discounts", "Discount")
    Discount.objects.filter(first_order_only=True).update(minimum_order_amount=Decimal("0.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0008_first_order_discount_active_window"),
    ]

    operations = [
        migrations.RunPython(clear_first_order_discount_minimum, migrations.RunPython.noop),
    ]
