# Generated by Django 5.2.14 on 2026-08-18 08:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_category_taxonomy_group'),
        ('discounts', '0009_first_order_discount_no_minimum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='buy_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='get_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_applications',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='reward_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='discount',
            name='reward_source',
            field=models.CharField(choices=[('cheapest', 'Cheapest eligible items in the cart'), ('reward_set', 'Items marked as reward on the discount rules')], default='cheapest', max_length=20),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discount_rules', to='categories.category'),
        ),
        migrations.AddField(
            model_name='discountrule',
            name='role',
            field=models.CharField(choices=[('eligible', 'Counts towards the buy quantity'), ('reward', 'Can be given as the reward')], default='eligible', max_length=20),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('percent', 'Percent'), ('bogo', 'Buy X get Y')], max_length=20),
        ),
    ]
