# Generated by Django 5.2.13 on 2026-04-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('manual', 'Manual'), ('order', 'Order'), ('cancellation', 'Cancellation'), ('refund', 'Refund')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'inventory_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold', models.PositiveIntegerField()),
                ('current_stock', models.PositiveIntegerField()),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'low_stock_alerts',
            },
        ),
    ]
