# Generated by Django 5.2.14 on 2026-06-11 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternationalShipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('destination_country', models.CharField(max_length=120)),
                ('destination_country_code', models.CharField(blank=True, max_length=2)),
                ('destination_region', models.CharField(blank=True, max_length=120)),
                ('service_name', models.CharField(max_length=120)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('delivery_time', models.CharField(blank=True, max_length=120)),
                ('handling_time', models.CharField(blank=True, max_length=120)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_item_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD')], default='USD', max_length=3)),
                ('duties_paid_by', models.CharField(choices=[('customer', 'Customer pays duties/taxes'), ('merchant', 'Merchant pays duties/taxes'), ('included', 'Duties/taxes included')], default='customer', max_length=20)),
                ('customs_notes', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('shipping_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_shipping_options', to='shipping.shippingmethod')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='international_shipping_options', to='shipping.shippingzone')),
            ],
            options={
                'db_table': 'international_shipping',
                'ordering': ['sort_order', 'destination_country', 'service_name'],
                'indexes': [models.Index(fields=['is_active', 'destination_country_code'], name='internation_is_acti_3b73e1_idx'), models.Index(fields=['sort_order', 'destination_country'], name='internation_sort_or_b4b71b_idx')],
            },
        ),
    ]
