# Generated by Django 5.2.16 on 2026-07-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_internationalshipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='ups_service_code',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
    ]
